export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',

  TENANT_PROVISIONED = 'TENANT_PROVISIONED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  TENANT_DELETED = 'TENANT_DELETED',
  TENANT_PLAN_CHANGED = 'TENANT_PLAN_CHANGED',

  ROLE_SYNCED = 'ROLE_SYNCED',
  MEMBER_INVITED = 'MEMBER_INVITED',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',

  INVITATION_CREATED = 'INVITATION_CREATED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',

  ONBOARDING_STARTED = 'ONBOARDING_STARTED',
  ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',
  ONBOARDING_STEP_COMPLETED = 'ONBOARDING_STEP_COMPLETED',

  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  PROJECT_ARCHIVED = 'PROJECT_ARCHIVED',

  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',

  COMMENT_CREATED = 'COMMENT_CREATED',
  COMMENT_DELETED = 'COMMENT_DELETED',

  SPRINT_CREATED = 'SPRINT_CREATED',
  SPRINT_STARTED = 'SPRINT_STARTED',
  SPRINT_COMPLETED = 'SPRINT_COMPLETED',

  ISSUE_CREATED = 'ISSUE_CREATED',
  ISSUE_UPDATED = 'ISSUE_UPDATED',
  ISSUE_DELETED = 'ISSUE_DELETED',
  ISSUE_BULK_MOVED = 'ISSUE_BULK_MOVED',
  BUG_REPORTED = 'BUG_REPORTED',

  MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',

  SETTINGS_GENERAL_UPDATED = 'SETTINGS_GENERAL_UPDATED',
  NOTIFICATION_PREFS_UPDATED = 'NOTIFICATION_PREFS_UPDATED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  ORG_DELETED = 'ORG_DELETED',
  ORG_SWITCHED = 'ORG_SWITCHED',

  SCHEMA_CREATED = 'SCHEMA_CREATED',
  MIGRATION_COMPLETED = 'MIGRATION_COMPLETED',
  TENANT_MIGRATION_RUN = 'TENANT_MIGRATION_RUN',
  RATE_LIMIT_HIT = 'RATE_LIMIT_HIT',

  TOKEN_REFRESH = 'TOKEN_REFRESH',
  TOKEN_REVOKED = 'TOKEN_REVOKED',

  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  WEBHOOK_PROCESSED = 'WEBHOOK_PROCESSED',
}
